services:
  db:
    image: mysql
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: product
    ports:
      - "3308:3306"
    restart: unless-stopped