services:
  db:
    image: mysql
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: inventory
    ports:
      - "3310:3306"
    restart: unless-stopped